# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ktmZBHSzGIpjSFTAxOAr9v2h7GDwEx6d

#Práctica 1
##Implementing a Data Warehouse with Django
####Mary José Martínez Castillo


####¿Qué es el Data Warehouse?

Un Data Warehouse es un gran almacén de datos e información que, además, recoge todos aquellos que son realmente necesarios para la realización de análisis e informes relacionado con el Business Intelligence (BI). Una parte fundamental en la toma de decisiones de las grandes empresas a la hora de establecer objetivos, establecer normativas y plantear riesgos.

Un almacén de datos centraliza y consolida grandes cantidades de datos de varias fuentes. Con el tiempo, crea un registro histórico que puede llegar a tener un valor incalculable para los científicos de datos y los analistas del negocio. 

##Evidencia de la práctica

<figure>
<center>
<img src='https://drive.google.com/file/d/1Ie7hrhRjdApOWRXw_GfG4gZGBn0xeGsK/view?usp=sharing' />
<figcaption>Imágen 1</figcaption></center>
</figure>

<figure>
<center>
<img src='https://drive.google.com/file/d/101DIWbxVKxX9edYvlXHE4RFirDzO6fwX/view?usp=sharing' />
<figcaption>Imágen 2</figcaption></center>
</figure>

<figure>
<center>
<img src='https://drive.google.com/open?id=1GwvMlyHQnFeRSJxZlty8Bbf5I2wmCBUN' />
<figcaption>Imágen 3</figcaption></center>
</figure>

<figure>
<center>
<img src='https://drive.google.com/open?id=1cEG_w8sXDHTD7mOTyTCCd1ybLyNm6ZLU' />
<figcaption>Imágen 4</figcaption></center>
</figure>
"""